

Max(1, 2, 123);
try do
    Doc("Max");
catch FunctionException do
    print "Ok";
end_try

